name: "TFTP Server"
description: "Temporary TFTP server for router flashing"
version: "1.0.1"
slug: "tftp_server"
arch:
  - amd64
init: false
startup: application
boot: manual
host_network: true
map:
  - share:rw
options: {}
schema: {}
